### PR TITLE
Pull pause container image from k8s.gcr.io

### PR DESCRIPTION
**Pull request by ashwani2k**
**What this PR does / why we need it**:
Replace pause container image registry to k8s.gcr.io to avoid CVE with glibc version used with google_containers/pause images. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Pause container image is now pulled from k8s.gcr.io/pause instead of gcr.io/google_containers/pause-amd64
```

### CODE REVIEW

**Review by himanshu-kun — APPROVED** [review]
/lgtm
maybe the tag could be updated as well

**Comment by ashwani2k** [comment]
> /lgtm maybe the tag could be updated as well

Thanks @himanshu-kun  for reviewing. 
The tag was already updated to 3.7 in the previous update, however what got missed was changing the container repository.

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Pull request merged**
